#!/usr/bin/env python3
"""Digi Mono's machine-list icons, 11 x 7 like the firmware's own: one 32-bit word a column, rows in bits
25-31 (the top row in bit 25, as the screen shows them). Prints them, or with --asm the lines for mods/digimono/glue.s."""
import sys

ICONS = {
    "sin": """
...........
..##.......
.#..#......
#....#....#
......#..#.
.......##..
...........""",
    "nois": """
.....#.....
.#...#...#.
.#.#.#...#.
####.#.#.##
.#.#.###.#.
.#...#.#...
.....#.....""",
    "saw": """
...........
....#....#.
...##...##.
..#.#..#.#.
.#..#.#..#.
#...##...##
...........""",
    "puls": """
...........
.###...###.
.#.#...#.#.
.#.#...#.#.
.#.#...#.#.
##.#####.##
...........""",
    "ens": """
...#....#..
..##...##..
.#.#..#.#..
#..#.#..#..
....#....#.
...##...##.
..#.#..#.#.""",
    "vo": """
...........
..#######..
.#.......#.
#..#####..#
.#.......#.
..#######..
...........""",
}
ORDER = ["sin", "nois", "saw", "puls", "ens", "vo"]


def grid(name):
    rows = [r for r in ICONS[name].strip("\n").split("\n")]
    assert len(rows) == 7 and all(len(r) == 11 for r in rows), name
    return rows


def words(name):
    g = grid(name)
    return [sum(1 << (25 + y) for y in range(7) if g[y][x] == "#") for x in range(11)]


if "--asm" in sys.argv:
    print("| generated by tools/gen_mono_icons.py --asm")
    for name in ORDER:
        w = words(name)
        print("digimono_icon_%s:" % name)
        print("        .long   BMP_VT, 11, 7, 1, digimono_px_%s, digimono_icon_mask, 0" % name)
        print("digimono_px_%s:" % name)
        print("        .long   " + ", ".join("0x%08x" % x for x in w[:6]))
        print("        .long   " + ", ".join("0x%08x" % x for x in w[6:]))
    print("digimono_icon_mask:")
    print("        .long   " + ", ".join(["0xfe000000"] * 6))
    print("        .long   " + ", ".join(["0xfe000000"] * 5))
else:
    for name in ORDER:
        print(name)
        for row in grid(name):
            print("  " + row)
