#!/usr/bin/env python3
"""Generate mods/digimono/macro_tables.h: the lookup tables Digi Mono's MACRO engines use, converted to
16-bit fixed point from the tables of Plaits (Emilie Gillet, MIT licence).

    python3 tools/gen_macro_tables.py <eurorack checkout> > mods/digimono/macro_tables.h

The source is plaits/resources.cc of github.com/pichenettes/eurorack. Float tables in -1..1 become Q15
(x 32768, clamped to +-32767), semitone tables Q8 (x 256); 16-bit tables are copied as they are.
"""
import re, sys

COPYRIGHT = """/* Generated by tools/gen_macro_tables.py from plaits/resources.cc (github.com/pichenettes/eurorack).
 *
 * Copyright 2016 Emilie Gillet.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
 * associated documentation files (the "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the
 * following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial
 * portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO
 * EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE
 * USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
"""

# name in resources.cc -> (name here, kind): "q15" converts a float table, "i16" copies a 16-bit one
TABLES = [
    ("lut_ws_inverse_tan", "MACRO_WS_INVERSE_TAN", "i16"),
    ("lut_ws_inverse_sin", "MACRO_WS_INVERSE_SIN", "i16"),
    ("lut_ws_linear", "MACRO_WS_LINEAR", "i16"),
    ("lut_ws_bump", "MACRO_WS_BUMP", "i16"),
    ("lut_ws_double_bump", "MACRO_WS_DOUBLE_BUMP", "i16"),
    ("lut_fold", "MACRO_FOLD", "q15"),
    ("lut_fold_2", "MACRO_FOLD_2", "q15"),
    ("lut_sine", "MACRO_SINE", "q15"),
    ("lut_4x_downsampler_fir", "MACRO_FIR4X", "q15"),
    ("lut_fm_frequency_quantizer", "MACRO_FM_RATIO", "q8"),     # semitones x 256
]


def load(path):
    s = open(path).read()
    out = {}
    for m in re.finditer(r'const\s+(\w+)\s+(\w+)\[\]\s*=\s*\{(.*?)\};', s, re.S):
        typ, name, body = m.groups()
        vals = [x.strip() for x in body.replace('\n', ' ').split(',') if x.strip()]
        try:
            vals = [float(v.rstrip('f')) if typ == 'float' else int(v, 0) for v in vals]
        except ValueError:
            continue
        out[name] = (typ, vals)
    return out


SHARED = {"MACRO_SINE"}


def main():
    res = load(sys.argv[1] + "/plaits/resources.cc")
    print(COPYRIGHT)
    print("#ifndef MACRO_TABLES_H\n#define MACRO_TABLES_H\n\n#include <stdint.h>\n")
    for src, name, kind in TABLES:
        typ, vals = res[src]
        if kind == "q15":
            vals = [max(-32767, min(32767, int(round(v * 32768)))) for v in vals]
        elif kind == "q8":
            vals = [int(round(v * 256)) for v in vals]
        print("#define %s_SIZE %d" % (name, len(vals)))
        # MACRO_SINE is also MONO SIN's, POLY SIN's and VO's (mono.c, through macro.h): one copy
        print("%sconst int16_t %s[%d] = {" % ("" if name in SHARED else "static ", name, len(vals)))
        for i in range(0, len(vals), 12):
            print("    " + ", ".join("%d" % v for v in vals[i:i + 12]) + ",")
        print("};\n")
    # stmlib's OnePole::tan<FREQUENCY_ACCURATE>(f) / f for f = 0..0.5 in 64 steps, Q12 (the SVF's g = f x this)
    import math
    pi = math.pi
    k = [pi, 3.333314036e-01 * pi ** 3, 1.333923995e-01 * pi ** 5, 5.33740603e-02 * pi ** 7,
         2.900525e-03 * pi ** 9, 9.5168091e-03 * pi ** 11]
    def tan_over_f(f):
        f2, acc = f * f, 0.0
        for c in reversed(k):
            acc = acc * f2 + c
        return acc
    vals = [int(round(tan_over_f(i / 128.0) * 4096)) for i in range(65)]
    print("#define MACRO_SVF_TAN_SIZE 65")
    print("static const uint16_t MACRO_SVF_TAN[65] = {")
    for i in range(0, 65, 12):
        print("    " + ", ".join("%d" % v for v in vals[i:i + 12]) + ",")
    print("};\n")
    # u / (1 + u): u = 0..1 in 64 steps, u = 1..16 in 240 steps (the drums' diodes and saturators), Q15;
    # stmlib's SoftLimit x (27 + x^2) / (27 + 9 x^2) for x = 0..3 in 128 steps (SoftClip), Q15
    def table(name, vals, typ="int16_t"):
        print("#define %s_SIZE %d" % (name, len(vals)))
        print("static const %s %s[%d] = {" % (typ, name, len(vals)))
        for i in range(0, len(vals), 12):
            print("    " + ", ".join("%d" % v for v in vals[i:i + 12]) + ",")
        print("};\n")
    q15 = lambda v: min(32767, int(round(v * 32768)))
    table("MACRO_RSAT_FINE", [q15((i / 64.0) / (1 + i / 64.0)) for i in range(65)])
    table("MACRO_RSAT_COARSE", [q15((1 + i / 16.0) / (2 + i / 16.0)) for i in range(241)])
    table("MACRO_SOFTCLIP", [q15((lambda x: x * (27 + x * x) / (27 + 9 * x * x))(3.0 * i / 128)) for i in range(129)])
    print("#endif")


if __name__ == "__main__":
    main()
