#!/usr/bin/env python3
"""Generate mods/digimono/mono_tables.h, the constant tables of the Digi Mono synth engine.

    python3 tools/gen_mono_tables.py            # write the header
    python3 tools/gen_mono_tables.py --check    # fail if the committed header is not what this writes

Everything here is computed from plain maths (no firmware content):
  SINE      513 x int16, one cycle of a sine (the 513th closes the cycle for the interpolation)
  SEMI_INC  12 x uint32, the phase increment at 48 kHz of MIDI notes 120..131 (the top octave)
  FINE      128 x uint16, 2^(i/(128*12)) - 1 in Q16: 1/128 of a semitone per step
  SEMI_UP   12 x uint16, 2^(s/12) - 1 in Q16: the ENS intervals within an octave
  DETUNE    128 x uint16, the unison detune of a knob value, 2^(cents/1200) - 1 in Q16,
            cents = 50 * (v/127)^2 (0 .. 50 cents, fine at the bottom of the knob)
  GAIN      128 x uint16, a knob value as a level in Q15, (v/127)^2 (0 .. 32768: 127 is exactly 1)
  RATE      128 x uint32, a knob value as an internal LFO's phase increment at 48 kHz,
            0.05 Hz * 400^(v/127) (0.05 .. 20 Hz)
  PENV1     65 x uint32, POLY SIN's pitch envelope: the decay a sample, e^(-1 / (tau * 48000)) in Q30, for a
            speed m = |ESPD - 64| of 1..64, tau = 2 s * (1 ms / 2 s)^((m - 1) / 63) (2 s .. 1 ms); m = 0: 1
  PENV32    65 x uint32, the same over 32 samples (a render block), PENV1^32 in Q30
"""
import argparse, math, os, sys

FS = 48000
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "mods", "digimono", "mono_tables.h")


def note_hz(n):
    return 440.0 * 2 ** ((n - 69) / 12)


def tables():
    t = {}
    t["SINE"] = ("int16_t", [int(round(32767 * math.sin(2 * math.pi * i / 512))) for i in range(513)])
    t["SEMI_INC"] = ("uint32_t", [int(round(note_hz(120 + s) / FS * 2 ** 32)) for s in range(12)])
    t["FINE"] = ("uint16_t", [int(round((2 ** (i / (128 * 12)) - 1) * 65536)) for i in range(128)])
    t["SEMI_UP"] = ("uint16_t", [int(round((2 ** (s / 12) - 1) * 65536)) for s in range(12)])
    t["DETUNE"] = ("uint16_t", [int(round((2 ** (50 * (v / 127) ** 2 / 1200) - 1) * 65536)) for v in range(128)])
    t["GAIN"] = ("uint16_t", [int(round(32768 * (v / 127) ** 2)) for v in range(128)])
    t["RATE"] = ("uint32_t", [int(round(0.05 * 400 ** (v / 127) / FS * 2 ** 32)) for v in range(128)])
    tau = [0] + [2.0 * (0.001 / 2.0) ** ((m - 1) / 63) for m in range(1, 65)]
    t["PENV1"] = ("uint32_t", [1 << 30] + [int(round(math.exp(-1 / (tau[m] * FS)) * 2 ** 30)) for m in range(1, 65)])
    t["PENV32"] = ("uint32_t", [1 << 30] + [int(round(math.exp(-32 / (tau[m] * FS)) * 2 ** 30)) for m in range(1, 65)])
    return t


def render():
    out = ["/* Generated by tools/gen_mono_tables.py - do not edit. Plain maths, no firmware content. */",
           "#ifndef MONO_TABLES_H", "#define MONO_TABLES_H", ""]
    for name, (ty, vals) in tables().items():
        out.append("static const %s MONO_%s[%d] = {" % (ty, name, len(vals)))
        for i in range(0, len(vals), 12):
            out.append("    " + ", ".join(str(v) for v in vals[i:i + 12]) + ",")
        out.append("};")
        out.append("")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        cur = open(OUT).read() if os.path.exists(OUT) else ""
        if cur != text:
            sys.exit("mono_tables.h is stale: run tools/gen_mono_tables.py")
        print("mono_tables.h is current")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w").write(text)
    print("wrote", os.path.relpath(OUT, ROOT))


if __name__ == "__main__":
    main()
